# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hello_world_nbdev',
                'doc_host': 'https://mtsyr3.github.io',
                'git_url': 'https://github.com/mtsyr3/hello_world_nbdev',
                'lib_path': 'hello_world_nbdev'},
  'syms': {'hello_world_nbdev.core': {'hello_world_nbdev.core.foo': ('core.html#foo', 'hello_world_nbdev/core.py')}}}
